### ISSUE TITLE
OS Selector, All Available

### ISSUE THREAD

**Issue by cstout1** [scriptingosx/fetch-installer-pkg#3]
Would it be possible to modify this excellent script to pull down and create a pkg for Catalina as it does for Big Sur? As it is right now I don't get an OS selector (only one Big Sur release is showing in the catalog at the time of writing this). I'm thinking something like installinstallmacos.py's OS selector, but the packaging method you've built here instead of the dmg build in the other.

**Comment by scriptingosx** [comment]
No, Apple doesn't provide Catalina or earlier versions of the "Install macOS" app in pkg format.

For Catalina and earlier, you can use `installinstallmacos.py` or `softwareupdate --fetch-full-installer` to download the application and `pkgbuild`, `quickpkg` or some other packaging tool to build your own pkg.

**Comment by cstout1** [comment]
Great, thank you. I didn't realize the pkg for Big Sur was coming directly from Apple. I appreciate the quick response.
